### ISSUE TITLE
启动报错./entry.sh: 1: [[: not found

### ISSUE THREAD

**Issue by howrain** [LQBing/docker-MiraiOK#1]

**Comment by lchkid** [comment]
自己改一下`entry.sh`，第一行加上`#!/bin/bash`，然后启动时加`-v $(pwd)/entry.sh:/workdir/entry.sh`

**Comment by howrain** [comment]
> 自己改一下`entry.sh`，第一行加上`#!/bin/bash`，然后启动时加`-v $(pwd)/entry.sh:/workdir/entry.sh`

谢谢解决了
